[alembic]
# 迁移脚本路径
script_location = migrations
# 日志文件（可选，默认使用 Python logging）
# log_file = alembic.log
# SQLAlchemy URL（由 Flask-Migrate 的 env.py 自动覆盖）
# sqlalchemy.url = driver://user:pass@localhost/dbname
# 版本号格式
# version_path_separator = /  # 默认 os.sep
# 包含模式
# include_schemas = False
# file_template = %%(rev)s_%%(slug)s

# 元数据配置
# compare_type = True
# compare_server_default = True
